# Default values for pf-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: staging

autoscaling:
  enabled: true

countries:
  ae:
    hosts:
      - staging.propertyfinder.ae
      - m.staging.propertyfinder.ae
  eg:
    hosts:
      - staging.propertyfinder.eg
      - m.staging.propertyfinder.eg
  lb:
    hosts:
      - staging.propertyfinder.com.lb
      - m.staging.propertyfinder.com.lb
  ma:
    hosts:
      - staging.sarouty.ma
      - m.staging.sarouty.ma
  sa:
    hosts:
      - staging.propertyfinder.sa
      - m.staging.propertyfinder.sa
      - staging.esimsar.com
      - m.staging.esimsar.com
