version: '3.7'

services:
  redis:
    image: redis
  datadog:
    image: gcr.io/datadoghq/agent:latest
    links:
     - redis
    environment:
     - DD_API_KEY=pub5955fb7c2154ba29aaf74c9773d47363
     - DD_SITE=datadoghq.com
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - '8126:8126'
  pfwebapp-builder:
    build: .
    ports:
      - '3000:3000'
      - '8081:8080'
    volumes:
      - .:/src
    command: 'tail -f /dev/null'
    environment:
      VIRTUAL_HOST: ~^web-app\.(.*)\.propertyfinder\.dev
      VIRTUAL_PORT: 3000
