version: '2.1'
services:
  pfwebapp-builder:
    image: 624165964329.dkr.ecr.ap-southeast-1.amazonaws.com/pf-web-app:builder-latest
    volumes:
      - .:/src

  pfwebapp-test:
    image: 624165964329.dkr.ecr.ap-southeast-1.amazonaws.com/pf-web-app:test-latest
    volumes:
      - .:/src
