import { BackendModelAgentInterface } from 'backend/model/agent/interface';

export const propertyAgentStub = (data: Partial<BackendModelAgentInterface> = {}): BackendModelAgentInterface => ({
  links: { profile: '/en/agent/mr-hamid-156740' },
  id: '156740',
  user_id: '28140',
  name: 'Mr Hamid',
  phone: '+971552273878',
  phone_did: null,
  phone_is_mobile: true,
  position: 'Agent',
  smart_ad: false,
  listing_level: 0,
  nationality: '',
  country_name: '',
  linkedin_address: '',
  ranking: 43,
  are_transactions_visible: true,
  agent_broker_license_no: '',
  verification_status: 'incomplete',
  transactions_count: 0,
  total_properties: 34,
  properties_residential_for_rent_count: 34,
  properties_residential_for_sale_count: 0,
  properties_commercial_count: 0,
  years_of_experience: null,
  languages: [],
  ...data,
});
