export enum AnalyticsPageNamesEnum {
  homePage = 'Portal Home',
  notFoundPage = 'Not Found',
  agentDetailsPage = 'Agent Detail',
  agentFindPage = 'Agent Home',
  agentSearchPage = 'Agent Serp',
  brokerDetailsPage = 'Broker Detail',
  brokerFindPage = 'Broker Home',
  brokerSearchPage = 'Broker Serp',
  propertySearchPage = 'Property Serp',
  propertyDetailsPage = 'Property Detail',
  propertyExpiredPage = 'Expired Property',
  savedPropertiesPage = 'Saved Properties',
  contactedPropertiesPage = 'Contacted Properties',
  ancillaryPage = 'Ancillary Page',
  homeValuationPage = 'Home Valuation',
  communityPage = 'Community Guides',
  mapSearchPage = 'Map Search',
  accountView = 'My Account Home',
  rentBuyCalculatorPage = 'Rent Buy Calculator',
  buildingReviewsPage = 'Building Reviews',
}
