# Default values for new-projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prId: latest

environment: prenv

sites:
  - mobile
  - desktop

autoscaling:
  enabled: false
  type: cpu
  targetUtilization: 60

replicaCount: 1
maxReplicaCount: 2

image:
  repository: 624165964329.dkr.ecr.ap-southeast-1.amazonaws.com/pf-web-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  name: pf-web-app-pf-local

ingress:
  enabled: true
  mobilePath: /(_next|((en|ar|fr)/(search|static|api/location/list|api/location/search|api/property-search/count|api/property-search/images)))(.*)
  desktopPath: /pf-web-app\/(.*)
  host: .k8s.propertyfinder.net

countries:
  ae:
    mobilePath: /(_next|((en|ar)/(static|api/pwa|search)))(.*)
    desktopPath: /pf-web-app\/(.*)
  bh:
    mobilePath: /(_next|((en|ar)/(static|api/pwa|search)))(.*)
    desktopPath: /pf-web-app\/(.*)
  eg:
    mobilePath: /(_next|((en|ar)/(static|api/pwa|search)))(.*)
    desktopPath: /pf-web-app\/(.*)
  qa:
    mobilePath: /(_next|((en|ar)/(static|api/pwa|search)))(.*)
    desktopPath: /pf-web-app\/(.*)
  sa:
    mobilePath: /(_next|((en|ar)/(static|api/pwa|search)))(.*)
    desktopPath: /pf-web-app\/(.*)
  lb: 
    mobilePath: /(_next|((en|ar)/(static|api/pwa|search)))(.*)
    desktopPath: /pf-web-app\/(.*)
  ma:
    mobilePath: /(_next|((ar|fr)/(static|api/pwa|search)))(.*)
    desktopPath: /pf-web-app\/(.*)

resources:
  limits:
    memory: 1280Mi
  requests:
    cpu: 50m
    memory: 700Mi

nodeSelector:
  nodegroup: app

tolerations: []

affinity: {}
