# Default values for new-projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prId: latest

environment: prenv

sites:
  - mobile
  - desktop

autoscaling:
  enabled: false
  type: cpu
  targetUtilization: 60
  
replicaCount: 1
maxReplicaCount: 2

image:
  repository: 624165964329.dkr.ecr.ap-southeast-1.amazonaws.com/pf-web-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  name: pf-web-app-pf-local

ingress:
  enabled: true
  kind: both
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # kubernetes.io/tls-acme: "true"
  mobilePath: /pf-web-app\/(.*)
  desktopPath: /pf-web-app\/(.*)
  tls: []
  #  - secretName: chart-example-tls
  host: .k8s.propertyfinder.net

countries:
  ae: {}
  bh: {}
  eg: {}
  qa: {}
  sa: {}

resources:
  limits:
    memory: 1280Mi
  requests:
    cpu: 50m
    memory: 700Mi

nodeSelector:
  nodegroup: app

tolerations: []

affinity: {}
