# Default values for pf-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: production
recaptcha_key: 6LcCK8EUAAAAALLeZpmtWq2EG1tM7KKyxSG7rchL
snowplow_host: c.propertyfinderdata.com

autoscaling:
  enabled: true

replicaCount: 2
maxReplicaCount: 20

countries:
  ae:
    hosts:
      - www.propertyfinder.ae
      - m.propertyfinder.ae
  bh:
    hosts:
      - www.propertyfinder.bh
      - m.propertyfinder.bh
  eg:
    hosts:
      - www.propertyfinder.eg
      - m.propertyfinder.eg
  qa:
    hosts:
      - www.propertyfinder.qa
      - m.propertyfinder.qa
  sa:
    hosts:
      - www.propertyfinder.sa
      - m.propertyfinder.sa
      - www.esimsar.com
      - m.esimsar.com
  lb:
    hosts:
      - www.propertyfinder.com.lb
  ma:
    hosts:
      - www.propertyfinder.ma
      - www.sarouty.ma

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 700Mi
