export enum TealiumPageEventEnum {
  homePage = 'home_page_view',
  notFoundPage = 'view',
  agentDetailsPage = 'find_agent_details_view',
  agentFindPage = 'find_agent_view',
  agentSearchPage = 'find_agent_view',
  brokerDetailsPage = 'find_broker_details_view',
  brokerFindPage = 'find_broker_view',
  brokerSearchPage = 'find_broker_view',
  propertySearchPage = 'search_view',
  propertyDetailsPage = 'property_view',
  propertyExpiredPage = 'view',
  savedPropertiesPage = 'saved_properties_view',
  contactedPropertiesPage = 'contacted_properties_view',
  ancillaryPage = 'view',
  homeValuationPage = 'view',
  communityPage = 'community_guides_view',
  mapSearchPage = 'map_search_view',
  myAccountPage = 'account_view',
  rentBuyCalculatorPage = 'rent_vs_buy_calculator_view',
  buildingReviewsPage = 'building_reviews_page',
}
