{{- $data := .}}
{{- range $site := .Values.sites }}
{{- range $country, $config := $data.Values.countries }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "web-app.fullname" $data }}-{{ $country }}-{{ $site }}
  labels:
    {{- include "web-app.labels" $data | nindent 4 }}
spec:
  replicas: {{ $data.Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ template "web-app.name" $data }}-{{ $country }}-{{ $site }}
      release: {{ $data.Release.Name }}
      site: {{ $site }}
  template:
    metadata:
      annotations:
{{- include "web-app.deployment.annotations" $data | nindent 8 }}
        sidecar.istio.io/inject: "false"
        ad.datadoghq.com/{{ $data.Chart.Name }}-{{ $site }}.logs: '[{"source":"{{ template "web-app.fullname" $data }}-{{ $country }}-{{ $site }}","service":"{{ template "web-app.fullname" $data }}-{{ $country }}-{{ $site }}"}]'
      labels:
        app: {{ template "web-app.name" $data }}-{{ $country }}-{{ $site }}
        release: {{ $data.Release.Name }}
        site: {{ $site }}
        {{- include "web-app.datadogLabels" $data | nindent 8 }}
    spec:
      {{- if $data.Values.nodeSelector }}
      nodeSelector:
{{ $data.Values.nodeSelector | toYaml | indent 8 }}
      {{ end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "web-app.name" $data }}-{{ $country }}-{{ $site }}
      containers:
        - name: {{ $data.Chart.Name }}-{{ $site }}
          image: "{{ $data.Values.image.repository }}:{{ $data.Values.image.tag }}"
          imagePullPolicy: {{ $data.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_COUNTRY_CODE
              value: {{ $country }}
            {{- if eq $site "mobile" }}
            - name: NEXT_PUBLIC_MOBILE
              value: "1"
            {{- else}}
            - name: NEXT_PUBLIC_MOBILE
              value: ""
            {{- end }}
            - name: ENVIRONMENT
              value: {{ $data.Values.environment }}
            - name: NEXT_PUBLIC_RECAPTCHA
              value: {{ $data.Values.recaptcha_key }}
            - name: NEXT_PUBLIC_SNOWPLOW_HOST
              value: {{ $data.Values.snowplow_host }}
            {{- include "web-app.datadogVariables" $data | nindent 12 }}
{{- if $data.Values.resources }}
          resources:
{{ toYaml $data.Values.resources | indent 12 }}
{{- end }}
{{- end }}
{{- end }}
