{{- if .Values.ingress.enabled }}
{{- $root := . }}
{{- $releaseName := include "web-app.fullname" . -}}
{{- range $country, $config := .Values.countries }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $releaseName }}-{{ $country }}
  labels:
    {{- include "web-app.labels" $root | nindent 4 }}
    scheme: external
spec:
  gateways:
  - {{ $releaseName }}
  hosts:
  {{- if eq $root.Values.environment "prenv" }}
  - website-{{ $country }}-{{ $root.Release.Name  }}{{ $root.Values.ingress.host}}
  - m.website-{{ $country }}-{{ $root.Release.Name  }}{{ $root.Values.ingress.host}}
  {{- else}}
  {{- range $config.hosts}}
  - {{ . }}
  {{- end }}
  {{- end }}
  http:
  # This rule is just for prenv. This routes the traffic coming from
  # m.website to mobile pods.
  {{- if eq $root.Values.environment "prenv" }}
  - match:
    {{- range $mobilePath := $config.mobilePath }}
    - uri:
        regex: {{ $mobilePath }}
    {{- end }}
      headers:
        host:
          prefix: "m.website"
    route:
    - destination:
        host: {{ $country }}-{{ $root.Values.service.name }}-mobile
    retries:
      attempts: 5
      perTryTimeout: 10s
      retryOn: gateway-error,connect-failure,refused-stream
    timeout: "30s"
  {{- else }}
  - match:
    {{- range $mobilePath := $config.mobilePath }}
    - uri:
        regex: {{ $mobilePath }}
    {{- end }}
      headers:
        x-akamai-device-characteristics:
          regex: "is_mobile=true(.*)"
    route:
    - destination:
        host: {{ $country }}-{{ $root.Values.service.name }}-mobile
    retries:
      attempts: 5
      perTryTimeout: 10s
      retryOn: gateway-error,connect-failure,refused-stream
    timeout: "30s"
  {{- end }}
  # Defaults to desktop
  - match:
    {{- range $desktopPath := $config.desktopPath }}
    - uri:
        regex: {{ $desktopPath }}
    {{- end }}
    route:
    - destination:
        host: {{ $country }}-{{ $root.Values.service.name }}-desktop
    retries:
      attempts: 5
      perTryTimeout: 10s
      retryOn: gateway-error,connect-failure,refused-stream
    timeout: "30s"
{{- end }}
{{- end }}
