name: pf-web-app-tests-workflow
on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Create npmrc file
        run: |
          cat > .npmrc <<EOF
          //npm.pkg.github.com/:_authToken=${{ secrets.SUBMODULES_TOKEN }}
          @propertyfinder:registry=https://npm.pkg.github.com
          EOF

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run tests
        run: make run-tests
        
